2021-07-07T16:49:36.982848-05:00 [warning] [Alarm Handler] Alarm high_system_memory_usage is activated, System memory usage is higher than 70%
2021-07-07T17:46:05.014689-05:00 [warning] [Alarm Handler] Alarm high_system_memory_usage is activated, System memory usage is higher than 70%
2021-07-08T09:36:39.235372-05:00 [warning] [SYSMON] long_schedule warning: pid = <0.1962.0>, info: [{timeout,901}, {in,undefined}, {out,undefined}], [{initial_call,{proc_lib,init_p,5}},{current_function,{cowboy_http,loop,1}},{registered_name,[]},{status,waiting},{message_queue_len,0},{group_leader,<0.1568.0>},{priority,normal},{trap_exit,true},{reductions,3019},{last_calls,false},{catchlevel,1},{trace,0},{suspending,[]},{sequential_trace_token,[]},{error_handler,error_handler},{memory,230512},{total_heap_size,28690},{heap_size,...},{...}|...]
2021-07-08T09:37:20.863127-05:00 [warning] [Alarm Handler] Alarm high_system_memory_usage is activated, System memory usage is higher than 70%
2021-07-08T10:35:56.531282-05:00 [error] [MySQL] Can't connect to MySQL server: Connection refused.
2021-07-08T10:35:56.531243-05:00 [error] Error in process <0.4139.0> on node 'cerdomaldito@127.0.0.1' with exit value:, {{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,"mysql_conn.erl"},{line,160}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,"mysql_conn.erl"},{line,136}]}]}
2021-07-08T10:35:56.531405-05:00 [error] Supervisor: {<0.4136.0>,ecpool_worker_sup}. Context: start_error. Reason: {{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,"mysql_conn.erl"},{line,160}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,"mysql_conn.erl"},{line,136}]}]}. Offender: id={worker,1},pid=undefined.
2021-07-08T10:35:56.531598-05:00 [error] Supervisor: {<0.4134.0>,ecpool_pool_sup}. Context: start_error. Reason: {shutdown,{failed_to_start_child,{worker,1},{{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,"mysql_conn.erl"},{line,160}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,"mysql_conn.erl"},{line,136}]}]}}}. Offender: id=worker_sup,pid=undefined.
2021-07-08T10:35:56.531765-05:00 [error] crasher: initial call: ecpool_worker:init/1, pid: <0.4137.0>, registered_name: [], exit: {{{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,"mysql_conn.erl"},{line,160}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,"mysql_conn.erl"},{line,136}]}]},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,401}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.4136.0>,<0.4134.0>,emqx_auth_mysql_sup,<0.4132.0>], message_queue_len: 1, messages: [{'EXIT',<0.4136.0>,{shutdown,{failed_to_start_child,{worker,1},{{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,[...]},{line,...}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,...},{...}]}]}}}}], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 28, reductions: 4606; neighbours:
2021-07-08T10:35:56.532120-05:00 [error] Supervisor: {local,emqx_auth_mysql_sup}. Context: start_error. Reason: {shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,...},{...}]},{mysql_conn,'-connect/1-fun-0-',2,[{...}|...]}]}}}}}. Offender: id=emqx_auth_mysql,pid=undefined.
2021-07-08T10:35:56.532384-05:00 [error] crasher: initial call: application_master:init/4, pid: <0.4131.0>, registered_name: [], exit: {{bad_return,{{emqx_auth_mysql_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqx_auth_mysql,{shutdown,{...}}}}}},[{emqx_auth_mysql_app,start,2,[{file,"emqx_auth_mysql_app.erl"},{line,38}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.4130.0>], message_queue_len: 1, messages: [{'EXIT',<0.4132.0>,normal}], links: [<0.4130.0>,<0.1431.0>], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 28, reductions: 245; neighbours:
2021-07-08T10:35:56.532748-05:00 [error] [Plugins] Load plugin emqx_auth_mysql failed, cannot start plugin emqx_auth_mysql for {bad_return,{{emqx_auth_mysql_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqx_auth_mysql,{shutdown,{failed_to_start_child,...}}}}}},[{emqx_auth_mysql_app,start,2,[{file,"emqx_auth_mysql_app.erl"},{line,38}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}}
2021-07-08T10:36:01.633638-05:00 [error] [MySQL] Can't connect to MySQL server: Connection refused.
2021-07-08T10:36:01.633610-05:00 [error] Error in process <0.4153.0> on node 'cerdomaldito@127.0.0.1' with exit value:, {{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,"mysql_conn.erl"},{line,160}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,"mysql_conn.erl"},{line,136}]}]}
2021-07-08T10:36:01.634087-05:00 [error] Supervisor: {<0.4150.0>,ecpool_worker_sup}. Context: start_error. Reason: {{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,"mysql_conn.erl"},{line,160}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,"mysql_conn.erl"},{line,136}]}]}. Offender: id={worker,1},pid=undefined.
2021-07-08T10:36:01.633946-05:00 [error] crasher: initial call: ecpool_worker:init/1, pid: <0.4151.0>, registered_name: [], exit: {{{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,"mysql_conn.erl"},{line,160}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,"mysql_conn.erl"},{line,136}]}]},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,401}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.4150.0>,<0.4148.0>,emqx_auth_mysql_sup,<0.4146.0>], message_queue_len: 0, messages: [], links: [<0.4150.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 28, reductions: 4329; neighbours:
2021-07-08T10:36:01.634352-05:00 [error] Supervisor: {<0.4148.0>,ecpool_pool_sup}. Context: start_error. Reason: {shutdown,{failed_to_start_child,{worker,1},{{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,"mysql_conn.erl"},{line,160}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,"mysql_conn.erl"},{line,136}]}]}}}. Offender: id=worker_sup,pid=undefined.
2021-07-08T10:36:01.634782-05:00 [error] Supervisor: {local,emqx_auth_mysql_sup}. Context: start_error. Reason: {shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,...},{...}]},{mysql_conn,'-connect/1-fun-0-',2,[{...}|...]}]}}}}}. Offender: id=emqx_auth_mysql,pid=undefined.
2021-07-08T10:36:01.634975-05:00 [error] crasher: initial call: application_master:init/4, pid: <0.4145.0>, registered_name: [], exit: {{bad_return,{{emqx_auth_mysql_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqx_auth_mysql,{shutdown,{...}}}}}},[{emqx_auth_mysql_app,start,2,[{file,"emqx_auth_mysql_app.erl"},{line,38}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.4144.0>], message_queue_len: 1, messages: [{'EXIT',<0.4146.0>,normal}], links: [<0.4144.0>,<0.1431.0>], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 28, reductions: 247; neighbours:
2021-07-08T10:36:01.635319-05:00 [error] [Plugins] Load plugin emqx_auth_mysql failed, cannot start plugin emqx_auth_mysql for {bad_return,{{emqx_auth_mysql_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqx_auth_mysql,{shutdown,{failed_to_start_child,...}}}}}},[{emqx_auth_mysql_app,start,2,[{file,"emqx_auth_mysql_app.erl"},{line,38}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}}
2021-07-08T10:36:16.263325-05:00 [error] [MySQL] Can't connect to MySQL server: Connection refused.
2021-07-08T10:36:16.263267-05:00 [error] Error in process <0.4171.0> on node 'cerdomaldito@127.0.0.1' with exit value:, {{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,"mysql_conn.erl"},{line,160}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,"mysql_conn.erl"},{line,136}]}]}
2021-07-08T10:36:16.263765-05:00 [error] Supervisor: {<0.4168.0>,ecpool_worker_sup}. Context: start_error. Reason: {{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,"mysql_conn.erl"},{line,160}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,"mysql_conn.erl"},{line,136}]}]}. Offender: id={worker,1},pid=undefined.
2021-07-08T10:36:16.263637-05:00 [error] crasher: initial call: ecpool_worker:init/1, pid: <0.4169.0>, registered_name: [], exit: {{{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,"mysql_conn.erl"},{line,160}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,"mysql_conn.erl"},{line,136}]}]},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,401}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.4168.0>,<0.4166.0>,emqx_auth_mysql_sup,<0.4164.0>], message_queue_len: 0, messages: [], links: [<0.4168.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 28, reductions: 4329; neighbours:
2021-07-08T10:36:16.264021-05:00 [error] Supervisor: {<0.4166.0>,ecpool_pool_sup}. Context: start_error. Reason: {shutdown,{failed_to_start_child,{worker,1},{{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,"mysql_conn.erl"},{line,160}]},{mysql_conn,'-connect/1-fun-0-',2,[{file,"mysql_conn.erl"},{line,136}]}]}}}. Offender: id=worker_sup,pid=undefined.
2021-07-08T10:36:16.264512-05:00 [error] Supervisor: {local,emqx_auth_mysql_sup}. Context: start_error. Reason: {shutdown,{failed_to_start_child,worker_sup,{shutdown,{failed_to_start_child,{worker,1},{{badmatch,{error,econnrefused}},[{mysql_conn,connect_socket,1,[{file,...},{...}]},{mysql_conn,'-connect/1-fun-0-',2,[{...}|...]}]}}}}}. Offender: id=emqx_auth_mysql,pid=undefined.
2021-07-08T10:36:16.264709-05:00 [error] crasher: initial call: application_master:init/4, pid: <0.4163.0>, registered_name: [], exit: {{bad_return,{{emqx_auth_mysql_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqx_auth_mysql,{shutdown,{...}}}}}},[{emqx_auth_mysql_app,start,2,[{file,"emqx_auth_mysql_app.erl"},{line,38}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}, ancestors: [<0.4162.0>], message_queue_len: 1, messages: [{'EXIT',<0.4164.0>,normal}], links: [<0.4162.0>,<0.1431.0>], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 28, reductions: 245; neighbours:
2021-07-08T10:36:16.265088-05:00 [error] [Plugins] Load plugin emqx_auth_mysql failed, cannot start plugin emqx_auth_mysql for {bad_return,{{emqx_auth_mysql_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,emqx_auth_mysql,{shutdown,{failed_to_start_child,...}}}}}},[{emqx_auth_mysql_app,start,2,[{file,"emqx_auth_mysql_app.erl"},{line,38}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}}
2021-07-08T10:52:19.921963-05:00 [warning] [SYSMON] long_schedule warning: pid = <0.1960.0>, info: [{timeout,830}, {in,undefined}, {out,undefined}], [{initial_call,{proc_lib,init_p,5}},{current_function,{cowboy_http,loop,1}},{registered_name,[]},{status,waiting},{message_queue_len,0},{group_leader,<0.1566.0>},{priority,normal},{trap_exit,true},{reductions,10491},{last_calls,false},{catchlevel,1},{trace,0},{suspending,[]},{sequential_trace_token,[]},{error_handler,error_handler},{memory,372368},{total_heap_size,46422},{heap_size,...},{...}|...]
2021-07-08T10:56:17.628443-05:00 [warning] from node@127.0.0.1:41848 [Channel] Client from node (Username: 'undefined') login failed for not_authorized
2021-07-08T10:56:18.638988-05:00 [warning] from node@127.0.0.1:41850 [Channel] Client from node (Username: 'undefined') login failed for not_authorized
2021-07-08T10:56:19.649028-05:00 [warning] from node@127.0.0.1:41852 [Channel] Client from node (Username: 'undefined') login failed for not_authorized
2021-07-08T10:56:20.657704-05:00 [warning] from node@127.0.0.1:41854 [Channel] Client from node (Username: 'undefined') login failed for not_authorized
2021-07-08T10:56:21.665861-05:00 [warning] from node@127.0.0.1:41856 [Channel] Client from node (Username: 'undefined') login failed for not_authorized
2021-07-08T10:56:22.674205-05:00 [warning] from node@127.0.0.1:41858 [Channel] Client from node (Username: 'undefined') login failed for not_authorized
2021-07-08T10:56:23.682343-05:00 [warning] from node@127.0.0.1:41860 [Channel] Client from node (Username: 'undefined') login failed for not_authorized
2021-07-08T10:56:24.690800-05:00 [warning] from node@127.0.0.1:41862 [Channel] Client from node (Username: 'undefined') login failed for not_authorized
2021-07-08T10:56:25.698539-05:00 [warning] from node@127.0.0.1:41866 [Channel] Client from node (Username: 'undefined') login failed for not_authorized
2021-07-08T10:56:26.706444-05:00 [warning] from node@127.0.0.1:41868 [Channel] Client from node (Username: 'undefined') login failed for not_authorized
2021-07-08T10:56:27.714504-05:00 [warning] from node@127.0.0.1:41870 [Channel] Client from node (Username: 'undefined') login failed for not_authorized
2021-07-08T10:58:40.235739-05:00 [warning] [SYSMON] long_schedule warning: pid = <0.2160.0>, info: [{timeout,447}, {in,undefined}, {out,undefined}], [{initial_call,{proc_lib,init_p,5}},{current_function,{cowboy_http,loop,1}},{registered_name,[]},{status,waiting},{message_queue_len,0},{group_leader,<0.1566.0>},{priority,normal},{trap_exit,true},{reductions,3003},{last_calls,false},{catchlevel,1},{trace,0},{suspending,[]},{sequential_trace_token,[]},{error_handler,error_handler},{memory,230512},{total_heap_size,28690},{heap_size,...},{...}|...]
2021-07-08T10:59:00.366226-05:00 [warning] mqttjs_c55aaf9089@127.0.0.1:41914 [Channel] Client mqttjs_c55aaf9089 (Username: '') login failed for not_authorized
2021-07-08T11:05:26.075639-05:00 [error] mqttjs_c55aaf9089@127.0.0.1:41956 [MySQL] Auth from mysql failed: not_authorized
2021-07-08T11:05:26.075848-05:00 [warning] mqttjs_c55aaf9089@127.0.0.1:41956 [Channel] Client mqttjs_c55aaf9089 (Username: 'roberto') login failed for not_authorized
